
# name: Greeetings

# on:
#   issues:
#     types: [opened]
#   pull_request:
#     types: [opened]

# jobs:
#   greeting:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/first-interaction@v1
#         with:
#           repo-token: ${{ secrets.GH_TOKEN }}
#           issue-message: 'Hello and welcome! Thank you for your interest in this project.'
#           pr-message: 'Hello and welcome! Thank you for your interest in this project.'
